---
title: "Group12_Nematodes"
output: html_document
---

```{r}
#install.packages("mapdata")
```


```{r}
library("tidyverse")
library("janitor")
library("naniar")
library("readxl")
library(shiny)
library(shinydashboard)
library(shinythemes)
library(fastmap)

library(leaflet)
library(mapdata)
```

```{r}
nematodes <- read.csv("data/dataset2.txt", header = TRUE, sep = "", stringsAsFactors = FALSE, fill = TRUE)
#this way cleans up the data nicely, can clean it up further and combine more data
```

```{r}
names(nematodes)
```

```{r}
treonis <- read.csv("data/Treonis.csv") %>% clean_names()

```

```{r}
soil <- read_excel("Soil_nematodes_all_data_final_Dryad.xlsx") %>% clean_names()
```


```{r} 
treonis_1 <- treonis %>%  #cleaning up the column names 
  rename_with(~str_replace(.x, "_identified", "")) 
 
```

```{r}
soil <- soil %>%
  replace_with_na_all(condition = ~.x == "NaN") %>%
  mutate(across(ends_with("herbivores"), ~ round(suppressWarnings(as.numeric(.)), 1)))

```

```{r}
treonis_2 <- treonis_1 %>% 
  pivot_longer(cols = 14:27, 
               names_to = "species", 
               values_to = "count")
```

```{r}
treonis_2 <- treonis_2 %>% 
  replace_with_na_all(condition = ~.x == 9999) 

```

```{r}
treonis_2 <- treonis_2 %>% 
  replace_with_na_all(condition = ~.x == "nd") 
```

```{r}
treonis_2 <- treonis_2 %>% #pivoted back because there were too many duplicates from the first pivot
  pivot_wider(names_from = "species", 
              values_from = "count")
```

```{r}
  write.csv(treonis_2, "data/treonis_2.csv", row.names = FALSE)
```



```{r}
names(soil)
```
```{r}
summary(soil)
miss_var_summary(soil)
```







### Made some categorical variables for the Soil data for trophic guilds. Feel free to use, change, or delete.
```{r}
soil <- soil %>% 
             mutate(herbivore_level = case_when(herbivores_percent_of_total <= 40 ~ "small",
                                              herbivores_percent_of_total > 40 & herbivores_percent_of_total <= 60 ~ "medium",
                                              herbivores_percent_of_total > 60 ~ "large"))
```

```{r}
soil <- soil %>% 
             mutate(fungivores_level = case_when(fungivores_percent_of_total <= 40 ~ "small",
                                             fungivores_percent_of_total > 40 & fungivores_percent_of_total <= 60 ~ "medium",
                                              fungivores_percent_of_total > 60 ~ "large"))
```

```{r}
soil <- soil %>% 
             mutate(bacterivores_level = case_when(bacterivores_percent_of_total <= 40 ~ "small",
                                              bacterivores_percent_of_total > 40 & bacterivores_percent_of_total <= 60 ~ "medium",
                                              bacterivores_percent_of_total > 60 ~ "large"))
```

```{r}
soil <- soil %>% 
             mutate(predators_level = case_when(predators_percent_of_total <= 40 ~ "small",
                                              predators_percent_of_total > 40 & predators_percent_of_total <= 60 ~ "medium",
                                              predators_percent_of_total > 60 ~ "large"))
```

```{r}
soil <- soil %>% 
             mutate(omnivores_level = case_when(omnivores_percent_of_total <= 40 ~ "small",
                                              omnivores_percent_of_total > 40 & omnivores_percent_of_total <= 60 ~ "medium",
                                              omnivores_percent_of_total > 60 ~ "large"))
```

```{r}
soil <- soil %>% 
             mutate(elevation_level = case_when(elevation <= 1695.5 ~ "small",
                                              elevation > 1695.5 & elevation <= 3109 ~ "medium",
                                              elevation > 3109 ~ "large"))
```



### Made a shiny dashboard with the plots I made. We can put everything together on a single dashboard later. I will am still adding titles and adjusting the variables, but this is what I have so far.
```{r, eval=F, echo=T}
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Nematode Soil Dashboard"),
  
  ## Sidebar content
  dashboardSidebar(
    sidebarMenu(
      
      menuItem("Soil and Climate", 
               tabName = "dashboard", 
               icon = icon("dashboard")),
      
      menuItem("Elevation and Soil Moisture", 
               tabName = "widgets", 
               icon = icon("th")),
      
      menuItem("Elevation and Diversity", 
               tabName = "tables", 
               icon = icon("th"))
    )
    ),
  
  ## Body content
  dashboardBody(
    
    tabItems(
  
      ## First tab content    
      tabItem(tabName = "dashboard",
        fluidRow(
          box(plotOutput("plot1", height = 250)), 
              selectInput("x", 
                "Select X Variable", 
                choices = c("conductivity", "p_h", "moisture", "temperature"), 
                selected = "conductivity"),
    
    selectInput("y", 
                "Select Y Variable", 
                choices = c("temperature_annual_range", "precipitation_of_wettest_month", "precipitation_seasonality", "precipitation_of_driest_month"), 
                selected = "temperature_annual_range")
          )
          ),

      ## Second tab item 
      tabItem(tabName = "widgets",
        fluidRow(
          box(plotOutput("plot2", height = 250)),
              selectInput("elevation", "Select elevation:", 
              choices=unique(soil$elevation_level)),
          )
          ),
    
      ## Third tab item
      tabItem(tabName = "tables",
        fluidRow(
          box(plotOutput("plot3", height = 250)),
             selectInput("x", 
                "Select X Variable", 
                choices = c("elevation_level"),
                selected = "elevation_level"),
          
          selectInput("y", 
                "Select Y Variable", 
                choices = c("enrichment_footprint", "composite_footprint"), 
                selected = "enrichment_footprint"),
          )
          )
          )
          )
          )
        
          
server <- function(input, output, session) {

  output$plot1 <- renderPlot({

    ggplot(data=soil, 
           aes_string(x=input$x, y=input$y, color="transect"))+
      geom_point(na.rm=T)+
      theme_light(base_size=14)+
      geom_smooth(method="lm", se=F)
  })
  
    output$plot2 <- renderPlot({
    
    soil %>% 
    filter(elevation_level==input$elevation) %>%
    ggplot(aes(x=moisture)) + 
    geom_density(color="black", fill="steelblue", alpha=0.6)
    
  })
    

    output$plot3 <- renderPlot({

 ggplot(data=soil, 
           aes_string(x=input$x, y=input$y, color="transect"))+
      geom_boxplot(na.rm=T)+
      theme_light(base_size=14)
      
    })
}

shinyApp(ui, server)
```





```{r}
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(title = "Nematode Soil Dashboard"),
  
  ## Sidebar content
  dashboardSidebar(
    sidebarMenu(
      
      menuItem("Elevation and Diversity", 
               tabName = "add_graph", 
               icon = icon("th")),
      
      menuItem("Elevation level and Species",
               tabName = "species",
               icon = icon("th"))
    )
    ),
  dashboardBody(tabItems(
     tabItem(tabName = "add_graph",
        fluidRow(
          box(plotOutput("plot4", height = 250)),
            
          
          selectInput("y", 
                "Select Y Variable", 
                choices = c("enrichment_footprint", "composite_footprint", "sigma_maturity_index"), 
                selected = "enrichment_footprint"),
            )),
     tabItem(tabName = "species",
             fluidRow(
               box(plotOutput("plot5", height=400, width = 400)),
          
          selectInput("x",
                      "Select X Variable",
                      choices = c("conductivity", "p_h", "moisture", "temperature","isothermality"),
                      selected = "conductivity"),
          
          selectInput("y",
                      "Select Y Variable",
                      choices = c("herbivores_percent_of_total", 
                                  "fungivores_percent_of_total",
                                  "bacterivores_percent_of_total",
                                  "predators_percent_of_total",
                                  "omnivores_percent_of_total"),
                      selected = "herbivores_percent_of_total"),
             ))
     # this is where the output will go
)))

server <- function(input, output) { 
      output$plot4 <- renderPlot({

 ggplot(data=soil, 
           aes_string(x="elevation_level", y=input$y, color="transect"))+
      geom_boxplot(na.rm=T)+
      theme_light(base_size=14)})
      
      output$plot5 <- renderPlot({
 ggplot(data = soil,
        aes_string(x=input$x, y=input$y, color="transect"))+
          geom_point(na.rm=T)+
          theme_light(base_size = 14)+
          geom_smooth(method=lm, se=T, color="black")
      })
}

shinyApp(ui, server)
```

```{r}
#install.packages("interp")
```



```{r}
library(ggplot2)
library(sf)
library(terra)
library(ggspatial)
library(ggnewscale)
library(ggtext)
library(readxl)
library(elevatr)
library(ggmap)
library(leaflet)
library(viridis)
library(interp)
```


```{r}

# Load dataset from Excel
file_path <- "Soil_nematodes_all_data_final_Dryad.xlsx"
df <- read_excel(file_path, sheet = "data_matrix")

# Convert to spatial format
df_sf <- st_as_sf(df, coords = c("Longitude", "Latitude"), crs = 4326)

x_limits <- c(74.2, 74.7)  # Longitude range
y_limits <- c(33.3, 33.7)  # Latitude range

# Fetch elevation data from AWS
elev_data <- get_elev_raster(df_sf, z = 10, src = "aws") 

elev_rast <- rast(elev_data)
crs(elev_rast) <- "EPSG:4326"  # Define CRS for elevation raster

# Crop and mask DEM to study area
elev_crop <- crop(elev_rast, ext(df_sf))
elev_masked <- mask(elev_crop, df_sf)

# Convert elevation raster to a dataframe for ggplot
elev_df <- as.data.frame(elev_masked, xy = TRUE)
colnames(elev_df) <- c("Longitude", "Latitude", "Elevation")

# Ensure sample locations also have CRS defined
st_crs(df_sf) <- 4326

# Generate Elevation Gradient Map
ggplot() +
  # Add the elevation raster as a gradient background
  geom_tile(data = elev_df, aes(x = Longitude, y = Latitude, fill = Elevation)) +
  scale_fill_viridis_c(name = "Elevation (m)", option = "plasma") +  # Adjust color gradient
  
  # Overlay sample locations (colored by Transect)
  geom_point(data = df, aes(x = Longitude, y = Latitude, color = Transect), size = 4) +
  scale_color_manual(values = c("red", "green", "blue", "purple")) +

  # Add labels for key locations (like Budhal)
  geom_text(data = df[df$Site == "Budhal",], aes(x = Longitude, y = Latitude, label = "Budhal"), 
            size = 5, color = "black", fontface = "bold", hjust = 1.2) +
  geom_point(data = df[df$Site == "Budhal",], aes(x = Longitude, y = Latitude), 
             color = "black", size = 3) +

  # Scale bar and North arrow
  annotation_scale(location = "br", width_hint = 0.2) +
  annotation_north_arrow(location = "tl", which_north = "true") +

  # Set correct coordinate reference system
  coord_sf(xlim = x_limits, ylim = y_limits, crs = 4326) +  # Ensures the proper projection
  
  # Theme settings
  theme_minimal() +
  labs(title = "Elevation Gradient with Sample Locations",
       x = "Longitude", y = "Latitude")

```





```{r}

# Register Google Maps API (Replace 'your_api_key' with your own key)
register_stadiamaps("bb553146-07e6-4634-b86c-af8ff1ad50f9", write = FALSE)

# Get the bounding box for the data points
lat <- range(soil$latitude)
lon <- range(soil$longitude)
bbox <- make_bbox(lon, lat, f = 0.03)

```

```{r}
# Download the terrain basemap
map1 <- get_stadiamap(bbox, maptype = "stamen_terrain", zoom=12)

```


```{r}

# Transect locations
data <- data.frame(
  Transect = c("Bakori", "Budhal", "Darhal", "Thanamandi"),
  Latitude = c(33.393844, 33.377822, 33.483548, 33.536140),
  Longitude = c(74.504130, 74.615964, 74.419256, 74.406322)
)

# Create map
ggmap(map1)+
  geom_point(data = data, aes(x=Longitude, y=Latitude, color=Transect), size=5) + # data= meaning not using pipes but layers
  labs(x= "Longitude", y= "Latitude", title="Transects on map")
```

```{r}
ggsave("Transect_Map.png", width = 10, height = 7, dpi = 300)
```



```{r}
# Convert basemap to raster format
map_raster <- as.raster(map1)

# Interpolate elevation for a smooth gradient
# Create a complete grid covering the bounding box
grid_x <- seq(min(lon), max(lon), length.out = 100)
grid_y <- seq(min(lat), max(lat), length.out = 100)
interp_elev <- interp(x = soil$longitude, y = soil$latitude, z = soil$elevation, 
                       xo = grid_x, yo = grid_y, duplicate = "mean", linear = TRUE)

# Convert to dataframe
elev_df <- expand.grid(Longitude = interp_elev$x, Latitude = interp_elev$y)
elev_df$elevation <- as.vector(interp_elev$z)

# ----  Corrected Elevation Gradient Map ---- #
ggplot() +
  annotation_raster(map_raster, xmin = min(lon), xmax = max(lon), 
                    ymin = min(lat), ymax = max(lat)) +  # Add basemap
  geom_raster(data = elev_df, aes(x = Longitude, y = Latitude, fill = elevation), alpha = 0.6) +  # Full elevation overlay
  scale_fill_gradient(low = "orange", high = "darkgreen", name = "Elevation (m)") +
  geom_point(data = soil, aes(x = longitude, y = latitude, color = transect), size = 4, alpha = 0.9) +  # Sample sites
  labs(title = "Elevation Gradient Map with Sample Sites", 
       x = "Longitude", y = "Latitude", color = "Transect Site") +
  coord_cartesian(xlim = lon_range, ylim = lat_range) +  # Ensure full coverage
  theme_minimal()
```




